package com.github.istin.dmtools.common.tracker.model;

public enum Workflow {

    UNKNOWN("Unknown"),
    NEW(Status.NEW),
    DRAFT(Status.DRAFT),
    ON_HOLD(Status.ON_HOLD),
    BLOCKED(Status.BLOCKED),
    BA_BLOCKED(Status.BA_BLOCKED),
    IN_BUSINESS_ANALYSIS(Status.IN_BUSINESS_ANALYSIS),
    BUSINESS_ANALYSIS(Status.BUSINESS_ANALYSIS),
    READY_FOR_ASSESSMENT(Status.READY_FOR_ASSESSMENT),
    IN_ASSESSMENT(Status.IN_ASSESSMENT),
    DEFINED(Status.DEFINED),
    WAITING_FOR_DESIGN(Status.WAITING_FOR_DESIGN),
    WAITING_FOR_VISUAL_DESIGN(Status.WAITING_FOR_VISUAL_DESIGN),
    IN_DESIGN(Status.IN_DESIGN),
    WAITING_FOR_VISUAL_DESIGN_APPROVE(Status.WAITING_FOR_VISUAL_DESIGN_APPROVE),
    WAITING_FOR_PO_APPROVAL(Status.WAITING_FOR_PO_APPROVAL),
    IN_GROOMING(Status.IN_GROOMING),
    READY_FOR_DEVELOPMENT(Status.READY_FOR_DEVELOPMENT),
    DEVELOPMENT_BLOCKED(Status.DEVELOPMENT_BLOCKED),
    BACKLOG(Status.BACKLOG),
    REOPENED(Status.REOPENED),
    IN_DEVELOPMENT(Status.IN_DEVELOPMENT),
    IN_REVIEW(Status.IN_REVIEW),
    CODE_REVIEW(Status.CODE_REVIEW),
    MERGED(Status.MERGED),
    DEVELOPMENT_COMPLETE(Status.DEVELOPMENT_COMPLETE),
    DEVELOPMENT_COMPLETED(Status.DEVELOPMENT_COMPLETED),
    READY_FOR_TESTING(Status.READY_FOR_TESTING),
    READY_FOR_RETEST(Status.READY_FOR_RETEST),
    READY_FOR_TEST(Status.READY_FOR_TEST),
    QA_BLOCKED(Status.QA_BLOCKED),
    TESTING_BLOCKED(Status.TESTING_BLOCKED),
    IN_QA(Status.IN_QA),
    IN_TESTING(Status.IN_TESTING),
    IN_VALIDATION(Status.IN_VALIDATION),
    BUG_TO_FIX(Status.BUG_TO_FIX),
    IN_SYSTEM_TEST(Status.IN_SYSTEM_TEST),
    READY_FOR_INTEGRATION(Status.READY_FOR_INTEGRATION),
    INTEGRATION_BLOCKED(Status.INTEGRATION_BLOCKED),
    IN_INTEGRATION(Status.IN_INTEGRATION),
    INTEGRATION_DONE(Status.INTEGRATION_DONE),
    PRODUCT_ACCEPTANCE_BLOCKED(Status.PRODUCT_ACCEPTANCE_BLOCKED),
    READY_FOR_ACCEPTANCE(Status.READY_FOR_ACCEPTANCE),
    IN_ACCEPTANCE(Status.IN_ACCEPTANCE),
    BUSINESS_VALIDATION(Status.BUSINESS_VALIDATION),
    DESIGN_ADJUSTMENTS(Status.DESIGN_ADJUSTMENTS),
    IMPLEMENTATION_REJECTED(Status.IMPLEMENTATION_REJECTED),
    IMPLEMENTATION_ACCEPTED(Status.IMPLEMENTATION_ACCEPTED),
    APPROVED(Status.APPROVED),
    READY_FOR_RELEASE(Status.READY_FOR_RELEASE),
    RESOLVED(Status.RESOLVED),
    CLOSED(Status.CLOSED),
    DONE(Status.DONE),
    REJECTED(Status.REJECTED),
    CANCELLED(Status.CANCELLED);

    private String name;

    Workflow(String name) {
        this.name = name;
    }

    public static Workflow safeValueOf(String name) {
        Workflow[] values = values();
        for (Workflow workflow : values) {
            if (workflow.name.equalsIgnoreCase(name)) {
                return workflow;
            }
        }
        return Workflow.UNKNOWN;
    }

}
