# Aider Gemini Assist
name: Aider Gemini Assist

on:
  workflow_dispatch:
    inputs:
      user_request:
        description: 'Your request for Aider'
        required: true
        type: string
      target_files:
        description: 'Files to include in context (comma-separated, optional)'
        required: false
        type: string
        default: ''
      model:
        description: 'Model to use with Aider'
        required: false
        type: choice
        default: 'gemini/gemini-2.5-flash-preview-05-20'
        options:
          - gemini/gemini-2.5-flash-preview-05-20
          - gemini/gemini-1.5-pro-latest
          - gemini/gemini-1.5-flash-latest
          - openai/gpt-4o-mini
          - openai/gpt-4o
          - anthropic/claude-3-5-sonnet-20241022
      max_tokens:
        description: 'Maximum tokens for context'
        required: false
        type: number
        default: 1000000
      enable_debug_logging:
        description: 'Enable comprehensive debug logging'
        required: false
        type: boolean
        default: true

permissions:
  contents: write
  pull-requests: write

jobs:
  ai-assist:
    name: AI Code Assistance (Aider)
    uses: IstiN/dmtools-agentic-workflows/.github/workflows/reusable-aider-assist.yml@main
    with:
      user_request: ${{ inputs.user_request }}
      target_files: ${{ inputs.target_files }}
      model: ${{ inputs.model }}
      max_tokens: ${{ inputs.max_tokens }}
      enable_debug_logging: ${{ inputs.enable_debug_logging }}
      
      # Use specific version for stability
      workflows_repo: 'IstiN/dmtools-agentic-workflows'
      workflows_ref: 'main'
      
    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
