name: Deploy to GCP Cloud Run

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build application JAR
        run: |
          ./gradlew clean :dmtools-server:bootJar -PbuildProfile=production -x test -x integrationTest
          ls -la dmtools-appengine.jar
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Configure Docker to use gcloud as credential helper
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/dmtools/dmtools:${{ github.run_number }}-${{ github.sha }} \
            --build-arg GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
            --build-arg GEMINI_DEFAULT_MODEL="${{ vars.GEMINI_DEFAULT_MODEL }}" \
            .

      - name: Push Docker image
        run: docker push us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/dmtools/dmtools:${{ github.run_number }}-${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dmtools \
            --image us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/dmtools/dmtools:${{ github.run_number }}-${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars="SPRING_PROFILES_ACTIVE=prod,GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},GEMINI_DEFAULT_MODEL=${{ vars.GEMINI_DEFAULT_MODEL }}" \
            --memory=1Gi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=5 \
            --timeout=900 \
            --revision-suffix=github-${{ github.run_number }} \
            --traffic=100 \
            --project=${{ vars.GCP_PROJECT_ID }}

      - name: Clean up old revisions
        run: |
          # Get all revisions except the latest one
          OLD_REVISIONS=$(gcloud run revisions list --service=dmtools --region=us-central1 --project=${{ vars.GCP_PROJECT_ID }} --format="value(metadata.name)" --limit=10 | tail -n +2)
          
          # Delete old revisions
          for revision in $OLD_REVISIONS; do
            if [ ! -z "$revision" ]; then
              echo "Deleting old revision: $revision"
              gcloud run revisions delete $revision --region=us-central1 --project=${{ vars.GCP_PROJECT_ID }} --quiet || echo "Failed to delete $revision"
            fi
          done

      - name: Get deployment URL
        run: |
          echo "Application deployed to: https://dmtools-431977789017.us-central1.run.app"
          gcloud run services describe dmtools --region=us-central1 --project=${{ vars.GCP_PROJECT_ID }} --format="value(status.url)" 