name: Deploy to GCP Cloud Run

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build JAR for production
        run: |
          ./gradlew clean build :dmtools-server:bootJar -PbuildProfile=production -x test -x integrationTest
          echo "Build completed, checking for JAR files..."
          find . -name "*.jar" -type f | head -10
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify JAR exists and copy if needed
        run: |
          # Check if JAR exists in root
          if [ -f "dmtools-appengine.jar" ]; then
            echo "JAR found in root directory: $(ls -lh dmtools-appengine.jar)"
          else
            echo "JAR not found in root, checking dmtools-server/build/libs/"
            ls -la dmtools-server/build/libs/ || echo "dmtools-server/build/libs/ not found"
            
            # Try to find the JAR in build directories
            JAR_FILE=$(find . -name "dmtools-appengine.jar" -type f | head -1)
            if [ -n "$JAR_FILE" ]; then
              echo "Found JAR at: $JAR_FILE"
              cp "$JAR_FILE" ./dmtools-appengine.jar
              echo "Copied JAR to root: $(ls -lh dmtools-appengine.jar)"
            else
              echo "ERROR: dmtools-appengine.jar not found anywhere"
              echo "Available JAR files:"
              find . -name "*.jar" -type f
              exit 1
            fi
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Configure Docker to use gcloud as credential helper
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/dmtools/dmtools:${{ github.run_number }}-${{ github.sha }} \
            --build-arg GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
            --build-arg GEMINI_DEFAULT_MODEL="${{ vars.GEMINI_DEFAULT_MODEL }}" \
            .

      - name: Push Docker image
        run: docker push us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/dmtools/dmtools:${{ github.run_number }}-${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dmtools-github \
            --image us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/dmtools/dmtools:${{ github.run_number }}-${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars="SPRING_PROFILES_ACTIVE=prod,GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},GEMINI_DEFAULT_MODEL=${{ vars.GEMINI_DEFAULT_MODEL }}" \
            --memory=1Gi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=5 \
            --timeout=900 \
            --project=${{ vars.GCP_PROJECT_ID }}

      - name: Get deployment URL
        run: |
          URL=$(gcloud run services describe dmtools-github --region=us-central1 --project=${{ vars.GCP_PROJECT_ID }} --format="value(status.url)")
          echo "Application deployed to: $URL" 